[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.19.1",
    "argon2-cffi>=25.1.0",
    "deepface>=0.0.100",
    "email-validator>=2.3.0",
    "fastapi>=0.141.1",
    "greenlet>=3.5.4",
    "numpy>=2.5.2",
    "opencv-python-headless>=5.0.0.93",
    "pgvector>=0.5.0",
    "psycopg2-binary>=2.9.12",
    "psycopg[binary]>=3.3.4",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.2",
    "python-jose[cryptography]>=3.5.0",
    "python-multipart>=0.0.32",
    "sqlalchemy>=2.0.51",
    "tensorflow>=2.21.0",
    "tf-keras>=2.21.0",
    "uvicorn>=0.52.1",
]
