"""add unified behavioral profiles

Revision ID: 0fdf0874e7b4
Revises: 110fa304c704
Create Date: 2026-08-12 14:04:48.786195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0fdf0874e7b4'
down_revision: Union[str, Sequence[str], None] = '110fa304c704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_holidays_active_date'), table_name='holidays')
    op.drop_index(op.f('idx_holidays_date'), table_name='holidays')
    op.drop_table('holidays')
    op.drop_index(op.f('ix_notices_category'), table_name='notices')
    op.drop_index(op.f('ix_notices_expires_at'), table_name='notices')
    op.drop_index(op.f('ix_notices_is_published'), table_name='notices')
    op.drop_index(op.f('ix_notices_priority'), table_name='notices')
    op.drop_table('notices')
    op.add_column('behavioral_profiles', sa.Column('faculty_id', sa.Uuid(), nullable=True))
    op.alter_column('behavioral_profiles', 'student_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_behavioral_profiles_faculty_id'), 'behavioral_profiles', ['faculty_id'], unique=True)
    op.create_foreign_key(None, 'behavioral_profiles', 'faculty', ['faculty_id'], ['id'], ondelete='CASCADE')
    op.create_check_constraint('behavioral_profile_one_person_type', 'behavioral_profiles', '\n            (\n                student_id IS NOT NULL\n                AND faculty_id IS NULL\n            )\n            OR\n            (\n                student_id IS NULL\n                AND faculty_id IS NOT NULL\n            )\n            ')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('behavioral_profile_one_person_type', 'behavioral_profiles', type_='check')
    op.drop_constraint(None, 'behavioral_profiles', type_='foreignkey')
    op.drop_index(op.f('ix_behavioral_profiles_faculty_id'), table_name='behavioral_profiles')
    op.alter_column('behavioral_profiles', 'student_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('behavioral_profiles', 'faculty_id')
    op.create_table('notices',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('GENERAL', 'ACADEMIC', 'ATTENDANCE', 'EXAM', 'EVENT', 'HOLIDAY', 'IMPORTANT', name='notice_category'), autoincrement=False, nullable=False),
    sa.Column('priority', postgresql.ENUM('LOW', 'NORMAL', 'HIGH', 'URGENT', name='notice_priority'), autoincrement=False, nullable=False),
    sa.Column('is_published', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('notices_pkey'))
    )
    op.create_index(op.f('ix_notices_priority'), 'notices', ['priority'], unique=False)
    op.create_index(op.f('ix_notices_is_published'), 'notices', ['is_published'], unique=False)
    op.create_index(op.f('ix_notices_expires_at'), 'notices', ['expires_at'], unique=False)
    op.create_index(op.f('ix_notices_category'), 'notices', ['category'], unique=False)
    op.create_table('holidays',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('holiday_type', sa.VARCHAR(length=30), server_default=sa.text("'public'::character varying"), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('holidays_pkey')),
    sa.UniqueConstraint('date', 'name', name=op.f('holidays_unique_date_name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_holidays_date'), 'holidays', ['date'], unique=False)
    op.create_index(op.f('idx_holidays_active_date'), 'holidays', ['is_active', 'date'], unique=False)
    # ### end Alembic commands ###
