"""update student model

Revision ID: 5e6a5509f059
Revises: e2d4b03570d9
Create Date: 2026-08-10 10:19:25.161863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e6a5509f059'
down_revision: Union[str, Sequence[str], None] = 'e2d4b03570d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('students', sa.Column('semester', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'semester')
    op.drop_column('students', 'gender')
    # ### end Alembic commands ###
